services:
  postgresql:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bootcamp_sys
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "bootcamp_sys" ]
      interval: 10s
      retries: 5
      start_period: 10s

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY: test
      AWS_SECRET_ACCESS_KEY: test
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      retries: 5
      start_period: 10s

  api:
    build: .
    container_name: api
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/bootcamp_sys?schema=public
    ports:
      - "3000:3000"
    depends_on:
      localstack:
        condition: service_healthy
      postgresql:
        condition: service_healthy
